version: "2"
services:
  ixo-world:
    environment:
      - REACT_APP_BLOCKCHAIN_NODE_URL=http://blockchain_uat.ixo.world:46657
      - REACT_APP_BLOCK_SYNC_URL=https://explorer_uat.ixo.world
      - REACT_APP_DEFAULT_IXO_NODE_ORIGIN=https://app_uat.ixo.world
      - REACT_APP_VIRAL_LOOPS_CAMPAIGN_ID=CvLyXeovTHHU0BYOm01ZxqLs-zI
  ixo-web:
    environment:
      - REACT_APP_BLOCK_SYNC_URL=https://block_sync_pandora.ixo.world
      - REACT_APP_IXO_WORLD_ORIGIN=https://ixo.world
      - REACT_APP_KYC_LINK=https://signup.ixo.world
      - REACT_APP_IXO_TOKEN_CONTRACT_ADDRESS=0x827a41c26784e0f51081e6d26687bff9c1c667e6
      - REACT_APP_PROJECT_REGISTRY_CONTRACT_ADDRESS=0xfe45b990a1dd890adfac13b0a9c77758cc83a862
      - REACT_APP_FEE_PER_CLAIM_FEE=0.6
      - REACT_APP_FEE_PER_EVALUATION=0.4
      - REACT_APP_FEE_OVERHEAD=1.3
      - REACT_APP_CHAIN_ID=bondschain-1
      - REACT_APP_BLOCKCHAIN_NODE_URL=https://ixo-dev-validator-1.simply-vc.com.mt/gaiacli_rest_server
      - REACT_APP_GAIA_URL=https://ixo-testnet-validator-mt.simply-vc.com.mt/gaiacli_rest_server
      - REACT_APP_NAME=IXO
